sudo: required
services: 
  - docker

before_install:
  - docker build -t csaboss/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true csaboss/react-test npm test -- --coverage

after_success:
  - docker_build -t csaboss/multi-client ./client
  - docker_build -t csaboss/multi-nginx ./nginx
  - docker_build -t csaboss/multi-server ./server
  - docker_build -t csaboss/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push csaboss/multi-client
  - docker push csaboss/multi-nginx
  - docker push csaboss/multi-server
  - docker push csaboss/multi-worker